name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.10.0'
        channel: 'stable'
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: flutter --version
    - run: npm -g i ganache-cli
    - run: ganache-cli &
    - run: flutter pub get
    - run: flutter test  --coverage
    - uses: codecov/codecov-action@v2
      with:
        files: lcov.info

