name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.10.0'
        channel: 'stable'
    - run: flutter --version
    - run: flutter pub get
    - run: flutter test

  testMinimumVersion:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '1.17.0'
          channel: 'stable'
      - run: flutter --version
      - run: flutter pub get
      - run: flutter test