
steps:
  - uses: actions/checkout@v2
  - uses: subosito/flutter-action@v2
    with:
      flutter-version: '2.8.0'
      channel: 'stable'
  - run: flutter --version
  - run: flutter pub get
  - run: flutter test